import { CheckBox, GridBox, ListView, ScrollView, VerticalBox } from "std-widgets.slint";

import { UiConfig } from "../config.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";

    HorizontalLayout {
        height: 24px;
        Text {
            font-size: 20px;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}

        CheckBox {
            horizontal-stretch: 0;
            text: "Disable widgets";
            checked <=> UiConfig.widgets-disabled;
        }
    }

    @children
}