image: fukamachi/sbcl
before_script:
- apt-get mercurial
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
- rustup default nightly
- hg clone https://lab.rwest.io/otom8/demo ~/quicklisp/local-projects/demo
stages:
  - build
  - test
  - deploy
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - make build
    - echo "Compile complete."
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - make test
lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - make fmt
    - echo "No lint issues found."
deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."