include_guard = "demo_h"
autogen_warning = "/* DO NOT TOUCH */"
include_version = true
language = "C"
cpp_compat = true
line_length = 88
documentation = true	
[parse]
parse_deps = true
include = ["obj","fig","libc"]
extra_bindings = ["obj","fig","libc"]
#expand = ["demo","obj"]
#[parse.expand]
#crates = ["demo"]