[package]
name = "obj"
version = "0.1.0"
edition = "2021"
[dependencies]
ron = "0.7.0"
bincode = "1.3.3"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
mime = "0.3.16"
regex = "1.5.4"
rusty_ulid = "0.11.0"
uuid = { version = "0.8", features = ["serde"] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "0.8", features = ["wasm-bindgen"] }
